[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "account-abstraction/=/home/mauro/w/account-abstraction/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
# Set ETH_RPC_URL in your environment, or replace with your Alchemy/Infura URL directly.
mainnet = "https://late-dimensional-patron.quiknode.pro/53b37fface8cb5ae4a38c099cf2507684fdfdbfe"
base = "https://late-dimensional-patron.base-mainnet.quiknode.pro/53b37fface8cb5ae4a38c099cf2507684fdfdbfe"
